[versions]
spring-boot = "3.4.0"
spring-depman = "1.1.6"
lombok = "1.18.36"
junit-jupiter = "5.10.0"
assertj = "3.24.2"
spotbugs = "6.0.26"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot" }

[plugins]
springboot = { id = "org.springframework.boot", version = "3.4.0" }
springdepman = { id = "io.spring.dependency-management", version = "1.1.6" }
spotbugs = { id = "com.github.spotbugs", version = "6.0.26" }
